### PR TITLE
Added the ability to enable and disable the blocking of frames

### PR DESCRIPTION
**Pull request by cbrand**
This adds two environment variables which remove the `X-Frame-Options` completely or allows the configuration to change the allowance to the `SAMEORIGIN` policy.

### CODE REVIEW

**Comment by solsson** [comment]
I hadn't noticed these directives in proxy_ssl.conf. What would be the rationale for keeping them in the proxy image at all. Can't the underlying service send such headers? Or does proxying introduce additional vulnerabilities?

Also I don't understand the echo "for this build". It'll be per container start that the directives are disabled, won't it?

**Comment by cbrand** [comment]
I agree. The "for this build" is not perfect here. I removed the wording there.

I would argue that the original author did want to provide some sane default security measures. And blocking frames in general is a good idea. While you could say, that this behavior should be left on the application side, especially when you think about running wordpress and other systems behind the proxy, which you installed "out of the box", I would say that it is a good idea to have as a default parameter the best possible security measures pre configured. And this in my opinion includes the blocking of frames.

**Comment by solsson** [comment]
Good answer.

**Comment by solsson** [comment]
I just triggered a new build on docker hub

**Pull request merged**
